AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
