inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  TargetRubyVersion: 2.6

Layout/AlignHash:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - 'config/initializers/simple_form.rb'

Layout/EmptyLines:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'

Lint/UnusedBlockArgument:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'spec/features/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'

Style/StringLiterals:
  Exclude:
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/initializers/assets.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
  EnforcedStyle: double_quotes
